
import Capa_Dato.Conexion;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class Exportar extends javax.swing.JFrame {
Conexion conexion = new Conexion();
    Connection cin = conexion.getConexion();
    PreparedStatement ps;
        static ResultSet res;
    /**
     * Creates new form Exportar
     */
    public Exportar() {
        initComponents();
        TextPrompt holder;
        holder = new TextPrompt("Introduzca el nombre del archivo", T_NombreArchivo);

    }
void impresion() {

        String rutaCar = "C:\\Josefa Ortiz de Dominguez\\Evaluaciones";
        File carpeta = new File(rutaCar);
        String nombre = T_NombreArchivo.getText();
        String rutaArch = "";

        if (T_NombreArchivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Introduzca un nombre para el archivo");
        }else{
            if (carpeta.exists()) {
                rutaArch = "C:\\Josefa Ortiz de Dominguez\\Evaluaciones\\" + nombre + ".xls";
                File file = new File(rutaArch);
                ExportarExcel excel = new ExportarExcel(TB_Evaluaciones, file, T_NombreArchivo.getText());
                excel.export();
                if(true){
                    JOptionPane.showMessageDialog(this, "Documento generado con exito \n" + "Espere...");
                }

            } else {
                carpeta.mkdirs();

                rutaArch = "C:\\Josefa Ortiz de Dominguez\\Evaluaciones\\" + nombre + ".xls";
                File file = new File(rutaArch);
                ExportarExcel excel = new ExportarExcel(TB_Evaluaciones, file, nombre);
                excel.export();
                if(true){
                    JOptionPane.showMessageDialog(this, "Documento generado con exito \n" + "Espere...");
                }
            }
        }
        
        try{
            ProcessBuilder p = new ProcessBuilder();
            p.command("cmd.exe", "/c", rutaArch);
            p.start();
        } catch (IOException ex) {
            Logger.getLogger(VerEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Se intentó abrir el documento pero ocurrió un error");
        }
}
public void CargarArticulo() {
        DefaultTableModel modelo = (DefaultTableModel) TB_Evaluaciones.getModel();
        modelo.setRowCount(1);
        res = conexion.Consulta("SELECT Alumnos.NombreAlumno, Parciales.ComprensionMundo, Parciales.LenguajeComunicacion, Parciales.PensamientoMatematico, Parciales.Artes, Parciales.EducacionFisica FROM Alumnos INNER JOIN Parciales ON Alumnos.CURPAlumno=Parciales.CURPAlumno");
        //contador numero progresivo
        int c = 1;
        try {
            while (res.next()) {
                Vector v = new Vector();
                v.add(String.valueOf(c));
                v.add(res.getString(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));
                v.add(res.getString(6));

                modelo.addRow(v);
                TB_Evaluaciones.setModel(modelo);
                c++;
            }
        } catch (SQLException e) {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TB_Evaluaciones = new javax.swing.JTable();
        btnMostrarDatos = new javax.swing.JButton();
        T_NombreArchivo = new javax.swing.JTextField();
        B_Exportar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formato de Exportacion");

        TB_Evaluaciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TB_Evaluaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"N.P.", "Nombre", "Comprension del mundo", "Lenguaje y comunicacion", "Pensamiento matematico", "Artes", "Educacion fisica"},
                {null, "", "", "", "", "", ""},
                {null, "", "", "", "", "", ""},
                {null, "", "", "", "", "", ""}
            },
            new String [] {
                "No. Progresivo", "Nombre del alumno", "Compresion del Mundo", "Leguaje y comunicacion", "Pensamiento matematico", "Artes", "Educacion Fisica"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TB_Evaluaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_EvaluacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TB_Evaluaciones);

        btnMostrarDatos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMostrarDatos.setText("Mostrar todos los datos");
        btnMostrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDatosActionPerformed(evt);
            }
        });

        B_Exportar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        B_Exportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Excel_logo.png"))); // NOI18N
        B_Exportar.setText("Exportar");
        B_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ExportarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jLabel1.setText("Formato de Exportacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(T_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(B_Exportar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrarDatos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMostrarDatos)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_NombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Exportar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TB_EvaluacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_EvaluacionesMouseClicked
        // TODO add your handling code here:
        /*try {
            int fila = TB_Evaluaciones.getSelectedRow();
            String curp = TB_Evaluaciones.getValueAt(fila, 0).toString();

            ps = cin.prepareStatement("SELECT CURPAlumno, NombreAlumno, NombreMadre, NombrePadre, Años, Meses, Direccion, TelefonoContacto FROM Alumnos WHERE CURPAlumno=?");
            ps.setString(1, curp);
            res = ps.executeQuery();

            while (res.next()) {
                //Nom_Usuario.setText(String.valueOf(curp));
                //Contraseña.setText(res.getString("NombreAlumno"));

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());

        }*/
    }//GEN-LAST:event_TB_EvaluacionesMouseClicked

    private void btnMostrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDatosActionPerformed
        // TODO add your handling code here:
        CargarArticulo();
    }//GEN-LAST:event_btnMostrarDatosActionPerformed

    private void B_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ExportarActionPerformed
        impresion();
    }//GEN-LAST:event_B_ExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exportar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Exportar;
    private javax.swing.JTable TB_Evaluaciones;
    private javax.swing.JTextField T_NombreArchivo;
    private javax.swing.JButton btnMostrarDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
